package Clases;
// Generated 07-mar-2016 16:02:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private int nidusuario;
     private String nombre;
     private String correo;
     private String contraseña;
     private Set registrousuarios = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String nombre, String correo, String contraseña) {
        this.nombre = nombre;
        this.correo = correo;
        this.contraseña = contraseña;
    }
    public Usuario(String nombre, String correo, String contraseña, Set registrousuarios) {
       this.nombre = nombre;
       this.correo = correo;
       this.contraseña = contraseña;
       this.registrousuarios = registrousuarios;
    }
   
     @Id 

    
    @Column(name="nidusuario", unique=true, nullable=false)
    public int getNidusuario() {
        return this.nidusuario;
    }
    
    public void setNidusuario(int nidusuario) {
        this.nidusuario = nidusuario;
    }

    
    @Column(name="nombre", nullable=false, length=40)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="correo", nullable=false, length=128)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="contraseña", nullable=false, length=10)
    public String getContraseña() {
        return this.contraseña;
    }
    
    public void setContraseña(String contraseña) {
        this.contraseña = contraseña;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getRegistrousuarios() {
        return this.registrousuarios;
    }
    
    public void setRegistrousuarios(Set registrousuarios) {
        this.registrousuarios = registrousuarios;
    }




}


